// Claude Code PreToolUse hook for the Bash tool: refuses the few shell
// commands that destroy work or write a generated file behind the other
// guard's back, and says why. Wired in .claude/settings.json.
//
// The permission deny list matches literal prefixes, so `git push --force`
// was refused while `git push -f`, `git reset --hard`, `git checkout -- .` and
// `rm -rf` on the working tree were not, and 38 `sed -i` edits in one week's
// sessions went around guard-generated.mjs, which only sees the Edit and
// Write tools. AGENTS.md forbids both; this is what enforces it.
//
// Exit 2 blocks the call and shows the message. Everything else exits 0; a
// hook that second-guesses ordinary commands is one that gets disabled.

import { readFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { PROTECTED } from './protected.mjs';

let input = {};
try { input = JSON.parse(readFileSync(0, 'utf8')); } catch { process.exit(0); }
const raw = String(input.tool_input?.command ?? '');
if (!raw) process.exit(0);

/**
 * The command with its heredoc bodies removed.
 *
 * A heredoc body is text being written to a file, not a command being run:
 * `cat > trials.txt <<'EOF'` followed by a line reading `rm -rf lib` writes
 * five words. Scanning it refused two of this hook's own test runs on the day
 * it was written, which is precisely how a guard earns its way into someone's
 * deny list. The exception is a body fed to a shell -- `bash <<EOF` -- where
 * the text really is executed, so those are left in.
 */
function withoutHeredocs(command) {
  if (/\b(ba|z|k|da)?sh\b[^\n]*<<-?\s*["']?\w/.test(command)) return command;
  const lines = command.split('\n');
  const kept = [];
  let closing = null;
  for (const line of lines) {
    if (closing !== null) {
      if (line.trim() === closing) closing = null;
      continue;
    }
    kept.push(line);
    // The last heredoc opened on this line is the one whose body follows.
    const opens = [...line.matchAll(/<<-?\s*(["']?)(\w+)\1/g)];
    if (opens.length) closing = opens[opens.length - 1][2];
  }
  return kept.join('\n');
}

const command = withoutHeredocs(raw);

const refuse = message => { console.error('Blocked: ' + message + ' If Alejandro asked for exactly this, say so and ask him to run it.'); process.exit(2); };

// Commands that throw work away. Each is named, so the message can say what
// to do instead.
const DESTRUCTIVE = [
  [/\bgit\s+push\b[^|;&]*(\s-[a-zA-Z]*f[a-zA-Z]*\b|\s--force(-with-lease)?\b|\s\+\S)/, 'a forced push rewrites history someone else may have pulled. Push a new commit instead.'],
  [/\bgit\s+reset\s+(--hard|--merge)\b/, 'git reset --hard discards uncommitted work in the tree. Use git stash if it must be set aside.'],
  [/\bgit\s+checkout\s+--\s/, 'git checkout -- <path> discards uncommitted changes to that file.'],
  [/\bgit\s+checkout\s+\.(\s|$)/, 'git checkout . discards every uncommitted change.'],
  [/\bgit\s+restore\b(?![^|;&]*--staged)/, 'git restore discards uncommitted changes to the files named.'],
  [/\bgit\s+clean\s+-[a-zA-Z]*[fdx]/, 'git clean deletes untracked files, which may be another session\'s work in this folder.'],
  [/\bgit\s+stash\s+(drop|clear)\b/, 'dropping a stash deletes the work it holds.'],
  [/\bgit\s+branch\s+-D\b/, 'git branch -D deletes a branch whether or not it is merged.'],
];
for (const [pattern, why] of DESTRUCTIVE) if (pattern.test(command)) refuse(why);

// Recursive deletion is fine on scratch, build output and the rebuildable
// caches, and nowhere else. The scratchpad is under the system temp directory;
// screenshots/ and .next/ are regenerated by the tools, node_modules by
// npm ci, and .cache/ by `npm run facts:generate -- --refresh`.
// Compared as whole path segments, so `rm -rf .next` and `rm -rf .next/cache`
// are both allowed while a directory that merely starts with the same letters
// is not. Bare names failed a startsWith against a trailing slash.
const SAFE_TO_DELETE = [os.tmpdir(), '/tmp', 'screenshots', '.next', 'node_modules', '.cache', '$SCRATCH'];
const SAFE_LIST = 'the temp directory, screenshots/, .next/, node_modules/ and .cache/';
const deletable = target => SAFE_TO_DELETE.some(prefix => target === prefix || target.startsWith(prefix + '/'));
// One command segment at a time: a target list ends at a newline or a
// separator, never at the next command. Reading on past it once reported
// `echo` and a JSON literal as things an `rm` was about to delete.
for (const segment of command.split(/[\n;|&]+/)) {
  const match = /\brm\s+((?:-[a-zA-Z]+\s+)*)(.*)$/.exec(segment);
  if (!match || !/r/i.test(match[1])) continue;
  const targets = match[2].trim().split(/\s+/).filter(token => token && !token.startsWith('-'));
  const unsafe = targets.filter(target => {
    const bare = target.replace(/^["']|["']$/g, '').replace(/^\.\//, '').replace(/\/+$/, '');
    return !deletable(bare);
  });
  if (unsafe.length) refuse('rm -r on ' + unsafe.join(', ') + ' deletes files in the working tree. Recursive deletion is allowed only under ' + SAFE_LIST + '.');
}

// A shell write aimed at a generated file: sed -i, a redirect, tee, cp or mv
// onto a path the Edit guard would refuse. Read the path with the tool that
// owns it, or say Alejandro asked for exactly this.
const root = process.env.CLAUDE_PROJECT_DIR ?? process.cwd();
const toRoot = token => {
  const bare = token.replace(/^["']|["']$/g, '').replace(/^\.\//, '');
  return path.isAbsolute(bare) ? path.relative(root, bare).split(path.sep).join('/') : bare;
};
const WRITES = /\bsed\s+-[a-zA-Z]*i|>{1,2}\s*|\btee\s+(-a\s+)?|\b(cp|mv)\s+(?:-[a-zA-Z]+\s+)*\S+\s+/g;
for (const write of command.matchAll(WRITES)) {
  // The rest of this command segment. A redirect, tee, cp or mv names its
  // target first; sed -i names the expression first and the files after it,
  // so every token of a sed segment is a candidate.
  const rest = command.slice(write.index + write[0].length).split(/[|;&]/)[0];
  const tokens = rest.trim().split(/\s+/).filter(Boolean);
  const targets = write[0].startsWith('sed') ? tokens : tokens.slice(0, 1);
  for (const target of targets) {
    const relative = toRoot(target);
    for (const [pattern, reason] of PROTECTED) {
      if (pattern.test(relative)) refuse(relative + ' is ' + reason + ' A shell write goes around the Edit guard, not around the rule.');
    }
  }
}

process.exit(0);
