// The files no agent edits by hand, and the tool that writes each one. Read by
// both guard hooks -- guard-generated.mjs for the Edit and Write tools,
// guard-bash.mjs for a shell command aimed at the same path -- and compared
// against "Do not touch without being asked" in AGENTS.md by
// scripts/check-rules.mjs, so the three descriptions of one rule cannot drift.

export const PROTECTED = [
  [/^public\/facts\/daily\/.+\.json$/, 'generated by npm run facts:generate. Edit data/daily-fact-overrides.json and rerun it (docs/DAILY_FACTS.md).'],
  [/^public\/fonts\/clock\//, 'generated by npm run fonts:clock. Edit the face list in scripts/fetch-clock-fonts.mjs and rerun it (docs/CLOCK.md).'],
  [/^app\/clock-fonts\.css$/, 'generated by npm run fonts:clock. Edit the face list in scripts/fetch-clock-fonts.mjs and rerun it (docs/CLOCK.md).'],
  [/^app\/horizon\.css$/, 'generated by npm run horizon, which traces the painted sky and the shed window off public/scenes/*.webp. Change the paintings and rerun it (docs/CLOCK.md).'],
  [/^public\/maps\/map-(water|lights|shadow)-\d\.webp$/, 'generated by python3 assets/map-design/segment-map.py, which segments the painted plates in public/maps. Change the paintings and rerun it (docs/FORECAST_MAP.md).'],
  [/^package-lock\.json$/, 'written by npm. Change package.json and run npm install, never edit the lockfile by hand.'],
  [/^\.codex\/hooks\.json$/, 'written by npm run agents:sync from .claude/settings.json. Edit that and rerun it.'],
  [/^\.agents\/skills\/source-command-.+\/SKILL\.md$/, 'written by npm run agents:sync from .claude/commands/. Edit the command there and rerun it.'],
  [/^render\.yaml$/, 'the record of a service created through the Render dashboard, which is the source of truth. Change the dashboard first, then bring this file to match it (docs/DEPLOYMENT.md).'],
];

// The other two entries in AGENTS.md's "Do not touch" list -- lib/transit.ts's
// stop names and lib/transitous.ts's headsigns -- are deliberately not here.
// Both files are mostly ordinary logic, and blocking every edit to them to
// protect a table of strings would cost more than it saves. check-rules.mjs
// keeps this list and that section of AGENTS.md in step instead.

// The reason a path is protected, or null when it is not.
export function protectedReason(relative) {
  for (const [pattern, reason] of PROTECTED) if (pattern.test(relative)) return reason;
  return null;
}
